### ISSUE TITLE
Syntax rules changed?

### ISSUE THREAD

**Issue by coryc5** [mat-mcloughlin/vscode-elixir#10]
It appears syntax rules have changed between the last few commits.

At 71e5b29/HEAD^ :
<img width="402" alt="screen shot 2016-06-25 at 12 55 08 pm" src="https://cloud.githubusercontent.com/assets/14861205/16358816/d45b4642-3ad4-11e6-8339-7007f74d40ce.png">

At master:
<img width="360" alt="screen shot 2016-06-25 at 12 55 35 pm" src="https://cloud.githubusercontent.com/assets/14861205/16358818/ddcb884a-3ad4-11e6-9da7-cc59109430d9.png">

Using the Monokai theme

**Comment by fr1zle** [comment]
Yes the rules changed, we now use the ones provided by the official atom package. Does the change look that extreme in other themes as well?

**Comment by coryc5** [comment]
From what I can tell, the issue seems to be limited to just Monokai-based themes.
