### ISSUE TITLE
Autocomplete when typing `do`

### ISSUE THREAD

**Issue by gregcline** [mat-mcloughlin/vscode-elixir#12]
When writing `do` the plugin wants to autocomplete to `doc`, so often end up deleting a doc comment I accidentally autocompleted, and if I want to avoid trailing whitespace I do a couple quick arrow strokes to get rid of the autocomplete prompt.

**Comment by philipgiuliani** [comment]
Yes it happens every time for me! :( Should really be fixed...

**Comment by fr1zle** [comment]
Noticed this as well, will look into it once i find some time

**Comment by lindend** [comment]
I also ran into this, however I found that creating a custom snippet for `do` works well as a workaround (File -> Preferences -> User Snippets):

```
	"do": {
		"prefix": "do",
		"body": [
			"do",
			"	$1",
			"end"
		]
	}
```

**Comment by Fahrradflucht** [comment]
Just a quick comment on @lindend's snippet. There are 3 spaces in front of the `$1`.
My linter freaked out on that. 😀

**Comment by lindend** [comment]
Weird, it's a tab in my vs code. Must have been some issues with my copy-paste transfer to the comment :).

**Comment by Fahrradflucht** [comment]
I looked into that some more and I think thats all there is to it. There just isn't a `do`-block snippet. I add that and do a PR.
