### ISSUE TITLE
Weird autocomplete on "do"

### ISSUE THREAD

**Issue by thousandsofthem** [mat-mcloughlin/vscode-elixir#14]
How to reproduce:
* Start writing new function
* Type `do`
* Hit enter
Editor will autocomplete do to full multiline `@doc` block

Expected:
Inserting new line, nothing fancy ;)

**Comment by philipgiuliani** [comment]
This is a duplicate of https://github.com/mat-mcloughlin/vscode-elixir/issues/12 . Close and add a comment there ;)
