### ISSUE TITLE
Intellisense sometimes inserts argument count

### ISSUE THREAD

**Issue by Fahrradflucht** [mat-mcloughlin/vscode-elixir#22]
This issue illustrates best with an example:

Open an Elixir file and write `__MODU` you will get completion for `__MODULE__/0`. The `/0` is useful when you look at the suggestion to see that it doesn't take any arguments, but it is pointless to insert it on `TAB`.

This doesn't happen all the time though. For example `String.first` does not have a `/1`.

I think removing the `/ARG_COUNT` from Intellisense completely would be the best and probably the easiest way since there are already the named arguments.

**Comment by mrkaspa** [comment]
I have this problem too

**Comment by scottmcpherson** [comment]
Same here. Are there any work arounds for this?

**Comment by Fahrradflucht** [comment]
> Same here. Are there any work arounds for this?

None that I know of

--

I just realized that there IS a situation where you want to have the argument count.
It's when you pass a function as  an argument to another function like so:
```elixir
[1, 2, 3]
|> Enum.map(to_string/1)
```

But that doesn't mean that this is a reason to not suggest the version without the count in Intellisense. In addition to that I would say that if there is a quick fix that removes the arg count and doesn't suggest the function with it I would prefer that over the current situation.

**Comment by mrkaspa** [comment]
Is this alive?

**Comment by mrkaspa** [comment]
This happened when autcompletes __MODULE__ I get __MODULE__/0
