### ISSUE TITLE
Quotes don't autocomplete

### ISSUE THREAD

**Issue by choiway** [mat-mcloughlin/vscode-elixir#27]
Is this intentional or did I miss a setting?

**Comment by Fahrradflucht** [comment]
I didn't test this but shouldn't this be fixed with #23 ?

If so then this is just a matter of @mat-mcloughlin pushing a version update to Visual Studio Marketplace.

**Comment by mat-mcloughlin** [comment]
I'm pushing tomorrow.

I apologise for my absence
