### ISSUE TITLE
Syntax Highlighting not working properly - VS1.7.1, Plugin: 0.0.8

### ISSUE THREAD

**Issue by MisterSpicy** [mat-mcloughlin/vscode-elixir#29]
I'm having some trouble getting the plugin to operate properly.  There appears to be some level of syntax highlighting, but not what seems is supposed to be there.

Intellisense also doesn't seem to run when typing, but if I force with cmd+space, the auto-complete window pops up, but nothing while typing automatically.  I uninstalled all other extensions and deleted all user and custom settings to ensure that they weren't interfering.

VSCode v1.7.1
vscode-elixir 0.0.8
OSX10.10

<img width="427" alt="screen shot 2016-11-14 at 11 52 16 am" src="https://cloud.githubusercontent.com/assets/2236561/20273859/d7260f78-aa60-11e6-968a-1dd5b013edc5.png">

**Comment by Fahrradflucht** [comment]
The syntax highlighting issue is due to your color scheme. If you for example switch to Solarized Light the modules would get highlighted just as you would expect.

I don't no why intellisense doesn't pop up for you. WFM at least. Are there suggestions in the Intellisense tray if you hit CMD+Space?

**Comment by bcardarella** [comment]
Is there a reason why only Solarized Light is supported?

**Comment by fr1zle** [comment]
Solarized Light was only used as an example. There a many different themes on the marketplace that provide a greater variety of colors.

**Comment by bcardarella** [comment]
I'm still not clear why this won't work with the default theme for vscode
