### ISSUE TITLE
Syntax highlighting for string interpolation

### ISSUE THREAD

**Issue by sschneider1207** [mat-mcloughlin/vscode-elixir#3]
It would be nice to have interpolated variables (e.g. `bar` in `"foo #{bar}"`) highlighted in a different way then strings do to make them stand out more clearly.  

For example the vim elixir plugin colors the `#{}` red, the actual variable uncolored, and the rest of the string purplish-pink.

**Comment by mat-mcloughlin** [comment]
Good idea, I'll look into it but it shouldn't be too hard

**Comment by philipgiuliani** [comment]
This has been fixed by the latest PR.

![bildschirmfoto 2016-06-16 um 20 39 38](https://cloud.githubusercontent.com/assets/5446019/16128815/7a6eca74-3402-11e6-8d53-c308962f2cd0.png)
