### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by mrkaspa** [mat-mcloughlin/vscode-elixir#31]

**Comment by Fahrradflucht** [comment]
I don't understand what this issue is about. frizzle merged a pull request just 16 days ago. And I think that if you fix an issue and provide a good pull request then there is a good chance that it will eventually get merged, maybe not the same or next day, but eventually.

**Comment by mat-mcloughlin** [comment]
sorry, it is still alive I just got behind on things

**Comment by mrkaspa** [comment]
@mat-mcloughlin thanks, is there a way to pull changes from master to use the lastest version of this plugin

**Comment by mat-mcloughlin** [comment]
@mrkaspa the latest release is in the market place now
