### ISSUE TITLE
Extension not working with Elixir 1.4

### ISSUE THREAD

**Issue by high1** [mat-mcloughlin/vscode-elixir#48]
On Windows 10, after updating to Elixir 1.4, autocomplete stops working. Reverting to 1.3 fixes it.
Windows 10, Visual Studio Code 1.8.1, Elixir 1.4

**Comment by fr1zle** [comment]
Hi, thanks for reporting. I think this a duplicate of #45 

Could you maybe check if you get the same errors?

**Comment by high1** [comment]
Getting the same exception. This is a duplicate of #45, so I will close this one, but the title on the active issue should be updated. Thanks.
