### ISSUE TITLE
`doctest` taking precedence over `do` in autocomplete

### ISSUE THREAD

**Issue by mattbaker** [mat-mcloughlin/vscode-elixir#50]
I'm noticing that `do` is autocompleting to `doctest` in ExUnit tests:

<img width="508" alt="screen shot 2017-02-02 at 10 27 31 pm" src="https://cloud.githubusercontent.com/assets/55462/22579575/cffe1720-e996-11e6-927f-6b00f0fcb9cc.png">

A few thoughts:

 * Should snippets like do/end take precedence over suggestions like this? 
 * Should `do` be a special case that takes priority because it's so fundamental syntactically?
 * Should `do` take precedence because it's a full match unlike the others in this screenshot?

I say all this having never actually thought about the problem of autocomplete before, and still being unfamiliar with vscode extensions (I'm poking around this repo), but I figured there's no harm in thinking out loud :)

**Comment by hoovercj** [comment]
I believe this is just how vs code handles suggestions.

See the [customizing intellisense](https://code.visualstudio.com/docs/editor/intellisense#_customizing-intellisense) section of the vscode docs. if you add `editor.snippetSuggestions: "top"` to your settings, you should see `do` before `doctest/2`.

Also, if you want to set this setting only for elixir files, check out the new [language specific settings](https://code.visualstudio.com/updates/v1_9#_language-specific-settings) feature in vscode 1.9

**Comment by mattbaker** [comment]
@hoovercj — That's super helpful, thanks so much @hoovercj. I'll close this (and, on the off chance I find a different fix, I'll try and contribute a PR)
