### ISSUE TITLE
Syntax highlighting not working

### ISSUE THREAD

**Issue by philipgiuliani** [mat-mcloughlin/vscode-elixir#7]
Hi! My syntax highlighting of elixir files is not working.

Plugin: 0.6.0
VSCode: 1.2.0

I recently used https://github.com/torrick/vscode-elixir-lang but i uninstalled it now and installed this plugin. 

As you can see in the bottom right corner the language has been recognized. I also tried a few Color themes. Torrick's one worked fine. Of course i tried closing and reopening it ect.. I have the same problem on both of my Mac's.

![bildschirmfoto 2016-06-13 um 21 45 03](https://cloud.githubusercontent.com/assets/5446019/16020838/1aa15840-31b0-11e6-8010-1328b51af1bd.png)

Could you maybe try reinstalling? Its some clean-install issue, or some conflict with torrick's old one?

**Comment by brettcrowell** [comment]
I'm experiencing the same issue on my Mac.  To get highlighting _today_, I was able to clone an old commit into the `~/.vscode/extensions` directory.

If it helps you in the immediate term, this is the commit I've fallen back to...
https://github.com/mat-mcloughlin/vscode-elixir/tree/31cea7b240f3b8dcc56055a8f0c0294d3f69b25d

**Comment by jknipp** [comment]
Same issue here on my Mac.

**Comment by Insanitariume** [comment]
Having the same issue here too, both on Windows and Mac, after updating the extension.

**Comment by philipgiuliani** [comment]
@mat-mcloughlin we need you!! :)

**Comment by mat-mcloughlin** [comment]
Looking into it now :)

**Comment by mat-mcloughlin** [comment]
@philipgiuliani can you confirm, are you just opening up and individual file or as part of opening a folder?

**Comment by philipgiuliani** [comment]
@mat-mcloughlin I've tried both possibilities.

Can you maybe try to remove the extension from .vscode/extensions and do a clean install? Maybe you have some development files left?

**Comment by mat-mcloughlin** [comment]
no I don't think its that. I only get the problem when its a single file. I'll push a branch up soon. If you can test it that would be great

**Comment by philipgiuliani** [comment]
Sure i can test that! :)

![bildschirmfoto 2016-06-15 um 12 13 35](https://cloud.githubusercontent.com/assets/5446019/16076238/9bb5ae84-32f2-11e6-8f97-e2673248d560.png)

**Comment by rkaramc** [comment]
@mat-mcloughlin syntax highlighting wasn't functional when I installed from the visual studio marketplace. I assume you are "vsce package"+"vsce publish"ing the extension? May need to explicitly copy the grammar/etc files into ./out for vsce to pick them up. I expect cloning the repo into .vscode/extensions won't trigger this issue.

**Comment by fr1zle** [comment]
This was caused by my PR @mat-mcloughlin Sorry i totally forgot to update it. Check out my comment in #8

**Comment by mat-mcloughlin** [comment]
@philipgiuliani you still have a folder open there. See below

![image](https://cloud.githubusercontent.com/assets/2362687/16098181/ab0f6184-3349-11e6-9fd1-a4858f3fcec6.png)

@fr1zle is looking good but there is just one small bug in it that I'm hoping he'll kindly fix

**Comment by mat-mcloughlin** [comment]
All seems to be good now
